function bgchange(){
    var abc = document.querySelector('.container')
    var abd = document.querySelector('.toggle')
    var abz = document.querySelector('.check')
    var bbc = document.querySelector('.fu')
    var bbs = document.querySelector('.su')
    var bbf = document.querySelector('.fu-1')

    var bba = document.querySelector('.name')
    var bbb = document.querySelector('.name-1')
    var bbd = document.querySelector('.name-2')
    var bbe = document.querySelector('.name-3')

    var cca = document.querySelector('.number')
    var ccb = document.querySelector('.number-1')
    var ccc = document.querySelector('.number-2')
    var ccd = document.querySelector('.number-3')

    var dda = document.querySelector('.com')
    var ddb = document.querySelector('.com-a')
    var ddc = document.querySelector('.com-b')
    var ddd = document.querySelector('.com-c')

    var eea = document.querySelector('.fi')
    var eeb = document.querySelector('.se')
    var eec = document.querySelector('.th')
    var eed = document.querySelector('.fo')

    var xxa = document.querySelector('.first')
    var xxb = document.querySelector('.second')
    var xxc = document.querySelector('.third')
    var xxd = document.querySelector('.fourth')
    var xxe = document.querySelector('.fifth')
    var xxf = document.querySelector('.sixth')
    var xxg = document.querySelector('.seventh')
    var xxh = document.querySelector('.eight')

    var xaa = document.querySelector('.info')
    var xbb = document.querySelector('.info-1')
    var xaz = document.querySelector('.sumeet')
    var xcc = document.querySelector('.num')
    var xdd = document.querySelector('.num-1')
    var xee = document.querySelector('.num-2')
    var xff = document.querySelector('.num-3')
    var xbz = document.querySelector('.sumeet-1')
    var xcz = document.querySelector('.sumeet-2')
    var xdz = document.querySelector('.sumeet-3')
    var xez = document.querySelector('.sumeet-4')
    var xfz = document.querySelector('.sumeet-5')
    var xgz = document.querySelector('.sumeet-6')
    var xhz = document.querySelector('.sumeet-7')
    var xiz = document.querySelector('.sumeet-8')
    var xjz = document.querySelector('.sumeet-9')

    abz.classList.toggle('activa-1')
    abc.classList.toggle('activa')
    abd.classList.toggle('activaa')
    bbc.classList.toggle('free')
    bbf.classList.toggle('free')
    bbs.classList.toggle('free-1')
    bba.classList.toggle('free-1')
    bbb.classList.toggle('free-1')
    bbd.classList.toggle('free-1')
    bbe.classList.toggle('free-1')

    cca.classList.toggle('free-2')
    ccb.classList.toggle('free-2')
    ccc.classList.toggle('free-2')
    ccd.classList.toggle('free-2')

    dda.classList.toggle('free-3')
    ddb.classList.toggle('free-3')
    ddc.classList.toggle('free-3')
    ddd.classList.toggle('free-3')

    eea.classList.toggle('free-4')
    eeb.classList.toggle('free-4')
    eec.classList.toggle('free-4')
    eed.classList.toggle('free-4')
    
    xxa.classList.toggle('free-4')
    xxb.classList.toggle('free-4')
    xxc.classList.toggle('free-4')
    xxd.classList.toggle('free-4')
    xxe.classList.toggle('free-4')
    xxf.classList.toggle('free-4')
    xxg.classList.toggle('free-4')
    xxh.classList.toggle('free-4')

    xaa.classList.toggle('free-5')
    xaz.classList.toggle('free-5')
    xbb.classList.toggle('free-5')
    xbz.classList.toggle('free-5')
    xcz.classList.toggle('free-5')
    xdz.classList.toggle('free-5')
    xez.classList.toggle('free-5')
    xfz.classList.toggle('free-5')
    xcc.classList.toggle('free-6')
    xdd.classList.toggle('free-6')
    xee.classList.toggle('free-6')
    xff.classList.toggle('free-6')
    xgz.classList.toggle('free-6')
    xhz.classList.toggle('free-6')
    xiz.classList.toggle('free-6')
    xjz.classList.toggle('free-6')
}